apiVersion: apps/v1
kind: Deployment
metadata:
  # This matches env.APP_NAME ("iris-classifier")
  name: iris-classifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris-classifier
  template:
    metadata:
      labels:
        app: iris-classifier
    spec:
      containers:
      - name: iris-classifier
        # This placeholder matches the CI file
        image: YOUR_IMAGE_PLACEHOLDER
        ports:
        # This port (80) matches your Dockerfile
        - containerPort: 80
        resources:
          requests:
            # This is required for the HPA to work
            cpu: "200m"