apiVersion: v1
kind: Service
metadata:
  # This matches env.SERVICE_NAME ("iris-classifier-svc")
  name: iris-classifier-svc
spec:
  type: LoadBalancer
  ports:
  # This port (80) matches the deployment
  - port: 80
    targetPort: 80
  selector:
    app: iris-classifier